In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [3]:
import pandas as pd

sales_df = pd.read_csv(r"D:\flipkart_data\sales_data.csv")

cancellation_df = pd.read_csv(r"D:\flipkart_data\cancellation_reports.csv")

earn_more_df = pd.read_csv(r"D:\flipkart_data\earn_more_reports.csv")

return_df = pd.read_csv(r"D:\flipkart_data\return_reports.csv")

search_traffic_df = pd.read_csv(r"D:\flipkart_data\Search_Traffic_Reports.csv")

In [4]:
sales_df.head(10)

,Seller GSTIN,Order ID,Order Item ID,Product Title/Description,FSN,SKU,HSN Code,Event Type,Event Sub Type,Order Type,...,Customer's Delivery State,Usual Price,Is Shopsy Order?,TDS Rate,TDS Amount,IRN,Business Name,Business GST Number,Beneficiary Name,IMEI
0,33AKZPJ6613M1ZJ,OD337392281679223100,337392281679223100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",94036000,Return,Return,Postpaid,...,Maharashtra,NaN,False,0.1,1.531,NaN,NaN,NaN,Shailee Verma,NaN
1,33AKZPJ6613M1ZJ,OD337442494105588100,337442494105588100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",94036000,Return,Return,Postpaid,...,West Bengal,NaN,False,0.1,0.637,NaN,NaN,NaN,Joydeep Barman,NaN
2,33AKZPJ6613M1ZJ,OD437539555726276100,437539555726276101,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",94036000,Sale,Sale,Prepaid,...,Uttar Pradesh,NaN,False,0.1,0.637,NaN,NaN,NaN,Gunjan Tripathi,NaN
3,33AKZPJ6613M1ZJ,OD437517196866690100,437517196866690100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",94036000,Sale,Sale,PartPaid,...,Karnataka,NaN,False,0.1,0.637,NaN,NaN,NaN,Nida Fatima,NaN
4,33AKZPJ6613M1ZJ,OD437517262241051100,437517262241051100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",94036000,Sale,Sale,PartPaid,...,Andhra Pradesh,NaN,False,0.1,0.637,NaN,NaN,NaN,Byna Jayasree,NaN
5,33AKZPJ6613M1ZJ,OD437419306208738100,437419306208738100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",94036000,Return,Return,Prepaid,...,Karnataka,NaN,False,0.1,1.486,NaN,NaN,NaN,Suresh,NaN
6,33AKZPJ6613M1ZJ,OD337507936581123400,337507936581123400,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",94036000,Sale,Sale,PartPaid,...,Karnataka,NaN,True,0.1,0.637,NaN,NaN,NaN,Imran Baig,NaN
7,33AKZPJ6613M1ZJ,OD337458298284925100,337458298284925100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",94036000,Sale,Sale,Postpaid,...,Tamil Nadu,NaN,False,0.1,0.637,NaN,NaN,NaN,Sekar Deva .M,NaN
8,33AKZPJ6613M1ZJ,OD337501032148051100,337501032148051100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",94036000,Sale,Sale,Postpaid,...,Madhya Pradesh,NaN,False,0.1,0.637,NaN,NaN,NaN,Rukmani,NaN
9,33AKZPJ6613M1ZJ,OD337502241577583100,337502241577583100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",94036000,Sale,Sale,Prepaid,...,Bihar,NaN,False,0.1,1.180,NaN,NaN,NaN,Mohd Arfat,NaN

In [5]:
sales_df.shape

(161, 60)

In [6]:
sales_df.columns

Index(['Seller GSTIN', 'Order ID', 'Order Item ID',
       'Product Title/Description', 'FSN', 'SKU', 'HSN Code', 'Event Type',
       'Event Sub Type', 'Order Type', 'Fulfilment Type', 'Order Date',
       'Order Approval Date', 'Item Quantity', 'Order Shipped From (State)',
       'Warehouse ID', 'Price before discount', 'Total Discount',
       'Seller Share', 'Bank Offer Share',
       'Price after discount (Price before discount-Total discount)',
       'Shipping Charges',
       'Final Invoice Amount (Price after discount+Shipping Charges)',
       'Type of tax', 'Taxable Value (Final Invoice Amount -Taxes)',
       'CST Rate', 'CST Amount', 'VAT Rate', 'VAT Amount', 'Luxury Cess Rate',
       'Luxury Cess Amount', 'IGST Rate', 'IGST Amount', 'CGST Rate',
       'CGST Amount', 'SGST Rate (or UTGST as applicable)',
       'SGST Amount (Or UTGST as applicable)', 'TCS IGST Rate',
       'TCS IGST Amount', 'TCS CGST Rate', 'TCS CGST Amount', 'TCS SGST Rate',
       'TCS SGST Amount', 'Total TCS Deducted', 'Buyer Invoice ID',
       'Buyer Invoice Date', 'Buyer Invoice Amount',
       'Customer's Billing Pincode', 'Customer's Billing State',
       'Customer's Delivery Pincode', 'Customer's Delivery State',
       'Usual Price', 'Is Shopsy Order?', 'TDS Rate', 'TDS Amount', 'IRN',
       'Business Name', 'Business GST Number', 'Beneficiary Name', 'IMEI'],
      dtype='object')

In [7]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 60 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Seller GSTIN                                                  161 non-null    object
 1   Order ID                                                      161 non-null    object
 2   Order Item ID                                                 161 non-null    int64
 3   Product Title/Description                                     161 non-null    object
 4   FSN                                                           161 non-null    object
 5   SKU                                                           161 non-null    object
 6   HSN Code                                                      161 non-null    int64
 7   Event Type                                                    161 non-null    object
 8   Event Sub Type                                                161 non-null    object
 9   Order Type                                                    161 non-null    object
 10  Fulfilment Type                                               161 non-null    object
 11  Order Date                                                    161 non-null    object
 12  Order Approval Date                                           161 non-null    object
 13  Item Quantity                                                 161 non-null    float64
 14  Order Shipped From (State)                                    161 non-null    object
 15  Warehouse ID                                                  0 non-null      float64
 16  Price before discount                                         161 non-null    float64
 17  Total Discount                                                161 non-null    float64
 18  Seller Share                                                  161 non-null    float64
 19  Bank Offer Share                                              161 non-null    float64
 20  Price after discount (Price before discount-Total discount)   161 non-null    float64
 21  Shipping Charges                                              161 non-null    float64
 22  Final Invoice Amount (Price after discount+Shipping Charges)  161 non-null    float64
 23  Type of tax                                                   161 non-null    int64
 24  Taxable Value (Final Invoice Amount -Taxes)                   161 non-null    float64
 25  CST Rate                                                      161 non-null    float64
 26  CST Amount                                                    161 non-null    float64
 27  VAT Rate                                                      161 non-null    float64
 28  VAT Amount                                                    161 non-null    float64
 29  Luxury Cess Rate                                              161 non-null    float64
 30  Luxury Cess Amount                                            161 non-null    float64
 31  IGST Rate                                                     161 non-null    float64
 32  IGST Amount                                                   161 non-null    float64
 33  CGST Rate                                                     161 non-null    float64
 34  CGST Amount                                                   161 non-null    float64
 35  SGST Rate (or UTGST as applicable)                            161 non-null    float64
 36  SGST Amount (Or UTGST as applicable)                          161 non-null    float64
 37  TCS IGST Rate                                                 161 non-null    float64
 38  TCS IGST Amount                                               161 non-null    float64
 39  TCS CGST Rate                                                 161 non-null    float64
 40  TCS CGST Amount                                               161 non-null    float64
 41  TCS SGST Rate                                                 161 non-null    float64
 42  TCS SGST Amount                                               161 non-null    float64
 43  Total TCS Deducted                                            161 non-null    float64
 44  Buyer Invoice ID                                              161 non-null    object
 45  Buyer Invoice Date                                            161 non-null    object
 46  Buyer Invoice Amount                                          161 non-null    float64
 47  Customer's Billing Pincode                                    161 non-null    int64
 48  Customer's Billing State                                      161 non-null    object
 49  Customer's Delivery Pincode                                   161 non-null    int64
 50  Customer's Delivery State                                     161 non-null    object
 51  Usual Price                                                   0 non-null      float64
 52  Is Shopsy Order?                                              161 non-null    bool
 53  TDS Rate                                                      161 non-null    float64
 54  TDS Amount                                                    161 non-null    float64
 55  IRN                                                           0 non-null      float64
 56  Business Name                                                 0 non-null      float64
 57  Business GST Number                                           0 non-null      float64
 58  Beneficiary Name                                              161 non-null    object
 59  IMEI                                                          0 non-null      float64
dtypes: bool(1), float64(37), int64(5), object(17)
memory usage: 74.5+ KB

In [8]:
sales_df.describe()

,Order Item ID,HSN Code,Item Quantity,Warehouse ID,Price before discount,Total Discount,Seller Share,Bank Offer Share,Price after discount (Price before discount-Total discount),Shipping Charges,...,Buyer Invoice Amount,Customer's Billing Pincode,Customer's Delivery Pincode,Usual Price,TDS Rate,TDS Amount,IRN,Business Name,Business GST Number,IMEI
count,1.610000e+02,161.0,161.0,0.0,161.000000,161.000000,161.000000,161.000000,161.000000,161.0,...,161.000000,161.000000,161.000000,0.0,1.610000e+02,161.000000,0.0,0.0,0.0,0.0
mean,3.897145e+17,94036000.0,1.0,NaN,1195.366460,-7.024845,1.341615,-8.366460,1188.341615,0.0,...,811.285714,553547.695652,553547.695652,NaN,1.000000e-01,1.006932,NaN,NaN,NaN,NaN
std,5.011149e+16,0.0,0.0,NaN,431.881924,13.873063,7.140646,18.168203,434.743000,0.0,...,973.491181,211319.922840,211319.922840,NaN,2.645007e-16,0.368409,NaN,NaN,NaN,NaN
min,3.373644e+17,94036000.0,1.0,NaN,289.000000,-76.000000,0.000000,-92.000000,289.000000,0.0,...,-1916.000000,121001.000000,121001.000000,NaN,1.000000e-01,0.245000,NaN,NaN,NaN,NaN
25%,3.375459e+17,94036000.0,1.0,NaN,752.000000,-6.000000,0.000000,-6.000000,752.000000,0.0,...,742.000000,412308.000000,412308.000000,NaN,1.000000e-01,0.637000,NaN,NaN,NaN,NaN
50%,4.373700e+17,94036000.0,1.0,NaN,1420.000000,0.000000,0.000000,0.000000,1391.000000,0.0,...,752.000000,563122.000000,563122.000000,NaN,1.000000e-01,1.179000,NaN,NaN,NaN,NaN
75%,4.375491e+17,94036000.0,1.0,NaN,1420.000000,0.000000,0.000000,0.000000,1420.000000,0.0,...,1420.000000,742137.000000,742137.000000,NaN,1.000000e-01,1.203000,NaN,NaN,NaN,NaN
max,4.376824e+17,94036000.0,1.0,NaN,1916.000000,0.000000,46.000000,0.000000,1916.000000,0.0,...,1916.000000,854318.000000,854318.000000,NaN,1.000000e-01,1.624000,NaN,NaN,NaN,NaN

In [9]:
for i, col in enumerate(sales_df.columns, start=1):
    print(i, col)

1 Seller GSTIN
2 Order ID
3 Order Item ID
4 Product Title/Description
5 FSN
6 SKU
7 HSN Code
8 Event Type
9 Event Sub Type
10 Order Type
11 Fulfilment Type
12 Order Date
13 Order Approval Date
14 Item Quantity
15 Order Shipped From (State)
16 Warehouse ID
17 Price before discount
18 Total Discount
19 Seller Share
20 Bank Offer Share
21 Price after discount (Price before discount-Total discount)
22 Shipping Charges
23 Final Invoice Amount (Price after discount+Shipping Charges)
24 Type of tax
25 Taxable Value (Final Invoice Amount -Taxes)
26 CST Rate
27 CST Amount
28 VAT Rate
29 VAT Amount
30 Luxury Cess Rate
31 Luxury Cess Amount
32 IGST Rate
33 IGST Amount
34 CGST Rate
35 CGST Amount
36 SGST Rate (or UTGST as applicable)
37 SGST Amount (Or UTGST as applicable)
38 TCS IGST Rate
39 TCS IGST Amount
40 TCS CGST Rate
41 TCS CGST Amount
42 TCS SGST Rate
43 TCS SGST Amount
44 Total TCS Deducted
45 Buyer Invoice ID
46 Buyer Invoice Date
47 Buyer Invoice Amount
48 Customer's Billing Pincode
49 Customer's Billing State
50 Customer's Delivery Pincode
51 Customer's Delivery State
52 Usual Price
53 Is Shopsy Order?
54 TDS Rate
55 TDS Amount
56 IRN
57 Business Name
58 Business GST Number
59 Beneficiary Name
60 IMEI

In [10]:
sales_clean = sales_df[
[
'Order ID',
'Order Item ID',
'Product Title/Description',
'FSN',
'SKU',
'Event Type',
'Event Sub Type',
'Order Type',
'Fulfilment Type',
'Order Date',
'Order Approval Date',
'Item Quantity',
'Order Shipped From (State)',
'Price before discount',
'Total Discount',
'Seller Share',
'Bank Offer Share',
'Price after discount (Price before discount-Total discount)',
'Shipping Charges',
'Final Invoice Amount (Price after discount+Shipping Charges)',
"Customer's Billing Pincode",
"Customer's Billing State",
"Customer's Delivery Pincode",
"Customer's Delivery State",
'Usual Price',
'Is Shopsy Order?',
'Beneficiary Name'
]
].copy()

In [11]:
sales_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 27 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Order ID                                                      161 non-null    object
 1   Order Item ID                                                 161 non-null    int64
 2   Product Title/Description                                     161 non-null    object
 3   FSN                                                           161 non-null    object
 4   SKU                                                           161 non-null    object
 5   Event Type                                                    161 non-null    object
 6   Event Sub Type                                                161 non-null    object
 7   Order Type                                                    161 non-null    object
 8   Fulfilment Type                                               161 non-null    object
 9   Order Date                                                    161 non-null    object
 10  Order Approval Date                                           161 non-null    object
 11  Item Quantity                                                 161 non-null    float64
 12  Order Shipped From (State)                                    161 non-null    object
 13  Price before discount                                         161 non-null    float64
 14  Total Discount                                                161 non-null    float64
 15  Seller Share                                                  161 non-null    float64
 16  Bank Offer Share                                              161 non-null    float64
 17  Price after discount (Price before discount-Total discount)   161 non-null    float64
 18  Shipping Charges                                              161 non-null    float64
 19  Final Invoice Amount (Price after discount+Shipping Charges)  161 non-null    float64
 20  Customer's Billing Pincode                                    161 non-null    int64
 21  Customer's Billing State                                      161 non-null    object
 22  Customer's Delivery Pincode                                   161 non-null    int64
 23  Customer's Delivery State                                     161 non-null    object
 24  Usual Price                                                   0 non-null      float64
 25  Is Shopsy Order?                                              161 non-null    bool
 26  Beneficiary Name                                              161 non-null    object
dtypes: bool(1), float64(9), int64(3), object(14)
memory usage: 33.0+ KB

In [12]:
sales_clean[['Item Quantity',
             'Order Shipped From (State)',
             'Shipping Charges']].nunique()

Item Quantity                 1
Order Shipped From (State)    1
Shipping Charges              1
dtype: int64

In [13]:
sales_clean = sales_df[
[
'Order ID',
'Order Item ID',
'Product Title/Description',
'FSN',
'SKU',
'Event Type',
'Event Sub Type',
'Order Type',
'Fulfilment Type',
'Order Date',
'Order Approval Date',
'Price before discount',
'Total Discount',
'Seller Share',
'Bank Offer Share',
'Price after discount (Price before discount-Total discount)',
'Final Invoice Amount (Price after discount+Shipping Charges)',
"Customer's Billing Pincode",
"Customer's Billing State",
"Customer's Delivery Pincode",
"Customer's Delivery State",
'Usual Price',
'Is Shopsy Order?',
'Beneficiary Name'
]
].copy()


During the initial data exploration, three columns were removed from the dataset:
- **Item Quantity**: Every order had a quantity of 1, so the column contained no variation.
- **Order Shipped From (State)**: All orders were shipped from the same state, making the column unsuitable for comparative analysis.
- **Shipping Charges**: Shipping charges were identical for every transaction and therefore did not provide any additional analytical value.

These columns were removed to simplify the dataset while preserving all information relevant to sales analysis.

In [14]:
sales_clean['Usual Price'].isnull().sum()

np.int64(161)

In [15]:
len(sales_clean)

161

In [16]:
sales_clean = sales_clean.drop(columns=['Usual Price'])



The **Usual Price** column contained 100% missing values and therefore did not provide any usable information for the analysis. Since the column could not contribute to any business insights or statistical analysis, it was removed from the cleaned dataset.

In [17]:
sales_clean.isnull().sum()

Order ID                                                        0
Order Item ID                                                   0
Product Title/Description                                       0
FSN                                                             0
SKU                                                             0
Event Type                                                      0
Event Sub Type                                                  0
Order Type                                                      0
Fulfilment Type                                                 0
Order Date                                                      0
Order Approval Date                                             0
Price before discount                                           0
Total Discount                                                  0
Seller Share                                                    0
Bank Offer Share                                                0
Price after discount (Price before discount-Total discount)     0
Final Invoice Amount (Price after discount+Shipping Charges)    0
Customer's Billing Pincode                                      0
Customer's Billing State                                        0
Customer's Delivery Pincode                                     0
Customer's Delivery State                                       0
Is Shopsy Order?                                                0
Beneficiary Name                                                0
dtype: int64



The cleaned dataset contains no missing values. Therefore, no imputation or row removal was required, and the dataset is ready for further analysis.

In [18]:
sales_clean.duplicated().sum()

np.int64(6)

In [19]:
sales_clean[sales_clean.duplicated()]

,Order ID,Order Item ID,Product Title/Description,FSN,SKU,Event Type,Event Sub Type,Order Type,Fulfilment Type,Order Date,...,Seller Share,Bank Offer Share,Price after discount (Price before discount-Total discount),Final Invoice Amount (Price after discount+Shipping Charges),Customer's Billing Pincode,Customer's Billing State,Customer's Delivery Pincode,Customer's Delivery State,Is Shopsy Order?,Beneficiary Name
88,OD437494218981748100,437494218981748100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-06 00:00:00,...,0.0,0.0,1420.0,1420.0,785681,Assam,785681,Assam,False,Tazim Ahmed
89,OD437494218981748100,437494218981748100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-06 00:00:00,...,0.0,0.0,1420.0,1420.0,785681,Assam,785681,Assam,False,Tazim Ahmed
90,OD437494218981748100,437494218981748100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-06 00:00:00,...,0.0,0.0,1420.0,1420.0,785681,Assam,785681,Assam,False,Tazim Ahmed
113,OD437577382826502100,437577382826502100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-16 00:00:00,...,0.0,0.0,752.0,752.0,743357,West Bengal,743357,West Bengal,False,Akshay Pradhan
114,OD437577382826502100,437577382826502100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-16 00:00:00,...,0.0,0.0,752.0,752.0,743357,West Bengal,743357,West Bengal,False,Akshay Pradhan
134,OD337622112495547100,337622112495547100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,Prepaid,NON_FBF,2026-05-21 00:00:00,...,0.0,-29.0,733.0,733.0,790105,Arunachal Pradesh,790105,Arunachal Pradesh,False,Kago Sima

In [20]:
sales_clean.duplicated().sum()

np.int64(6)

In [21]:
sales_clean[sales_clean.duplicated(keep=False)].sort_values(by='Order ID')

,Order ID,Order Item ID,Product Title/Description,FSN,SKU,Event Type,Event Sub Type,Order Type,Fulfilment Type,Order Date,...,Seller Share,Bank Offer Share,Price after discount (Price before discount-Total discount),Final Invoice Amount (Price after discount+Shipping Charges),Customer's Billing Pincode,Customer's Billing State,Customer's Delivery Pincode,Customer's Delivery State,Is Shopsy Order?,Beneficiary Name
133,OD337622112495547100,337622112495547100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,Prepaid,NON_FBF,2026-05-21 00:00:00,...,0.0,-29.0,733.0,733.0,790105,Arunachal Pradesh,790105,Arunachal Pradesh,False,Kago Sima
134,OD337622112495547100,337622112495547100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,Prepaid,NON_FBF,2026-05-21 00:00:00,...,0.0,-29.0,733.0,733.0,790105,Arunachal Pradesh,790105,Arunachal Pradesh,False,Kago Sima
87,OD437494218981748100,437494218981748100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-06 00:00:00,...,0.0,0.0,1420.0,1420.0,785681,Assam,785681,Assam,False,Tazim Ahmed
88,OD437494218981748100,437494218981748100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-06 00:00:00,...,0.0,0.0,1420.0,1420.0,785681,Assam,785681,Assam,False,Tazim Ahmed
89,OD437494218981748100,437494218981748100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-06 00:00:00,...,0.0,0.0,1420.0,1420.0,785681,Assam,785681,Assam,False,Tazim Ahmed
90,OD437494218981748100,437494218981748100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-06 00:00:00,...,0.0,0.0,1420.0,1420.0,785681,Assam,785681,Assam,False,Tazim Ahmed
112,OD437577382826502100,437577382826502100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-16 00:00:00,...,0.0,0.0,752.0,752.0,743357,West Bengal,743357,West Bengal,False,Akshay Pradhan
113,OD437577382826502100,437577382826502100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-16 00:00:00,...,0.0,0.0,752.0,752.0,743357,West Bengal,743357,West Bengal,False,Akshay Pradhan
114,OD437577382826502100,437577382826502100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-16 00:00:00,...,0.0,0.0,752.0,752.0,743357,West Bengal,743357,West Bengal,False,Akshay Pradhan

In [22]:
sales_clean = sales_clean.drop_duplicates()
sales_clean.duplicated().sum()

np.int64(0)



The dataset contained duplicate transaction records.

Upon inspection, the duplicate rows had identical values across all columns, including Order ID, Order Item ID, Product Description, Customer Information, Order Date, and Invoice Amount.

These duplicates appeared to be repeated exports of the same transaction rather than legitimate multiple purchases.

Therefore, duplicate records were removed to ensure accurate sales and revenue analysis.

In [23]:
sales_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 155 entries, 0 to 160
Data columns (total 23 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Order ID                                                      155 non-null    object
 1   Order Item ID                                                 155 non-null    int64
 2   Product Title/Description                                     155 non-null    object
 3   FSN                                                           155 non-null    object
 4   SKU                                                           155 non-null    object
 5   Event Type                                                    155 non-null    object
 6   Event Sub Type                                                155 non-null    object
 7   Order Type                                                    155 non-null    object
 8   Fulfilment Type                                               155 non-null    object
 9   Order Date                                                    155 non-null    object
 10  Order Approval Date                                           155 non-null    object
 11  Price before discount                                         155 non-null    float64
 12  Total Discount                                                155 non-null    float64
 13  Seller Share                                                  155 non-null    float64
 14  Bank Offer Share                                              155 non-null    float64
 15  Price after discount (Price before discount-Total discount)   155 non-null    float64
 16  Final Invoice Amount (Price after discount+Shipping Charges)  155 non-null    float64
 17  Customer's Billing Pincode                                    155 non-null    int64
 18  Customer's Billing State                                      155 non-null    object
 19  Customer's Delivery Pincode                                   155 non-null    int64
 20  Customer's Delivery State                                     155 non-null    object
 21  Is Shopsy Order?                                              155 non-null    bool
 22  Beneficiary Name                                              155 non-null    object
dtypes: bool(1), float64(6), int64(3), object(13)
memory usage: 28.0+ KB

In [24]:
sales_clean['Order Date'] = pd.to_datetime(sales_clean['Order Date'])

sales_clean['Order Approval Date'] = pd.to_datetime(sales_clean['Order Approval Date'])

In [25]:
sales_clean['Year'] = sales_clean['Order Date'].dt.year
sales_clean['Month'] = sales_clean['Order Date'].dt.month_name()
sales_clean['Month_Number'] = sales_clean['Order Date'].dt.month
sales_clean['Day'] = sales_clean['Order Date'].dt.day
sales_clean['Weekday'] = sales_clean['Order Date'].dt.day_name()

In [26]:
sales_clean.describe()

,Order Item ID,Order Date,Order Approval Date,Price before discount,Total Discount,Seller Share,Bank Offer Share,Price after discount (Price before discount-Total discount),Final Invoice Amount (Price after discount+Shipping Charges),Customer's Billing Pincode,Customer's Delivery Pincode,Year,Month_Number,Day
count,1.550000e+02,155,155,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.0,155.000000,155.000000
mean,3.885082e+17,2026-05-11 21:31:21.290322688,2026-05-11 21:31:21.290322688,1199.535484,-7.109677,1.393548,-8.503226,1192.425806,1192.425806,545079.464516,545079.464516,2026.0,4.883871,15.380645
min,3.373644e+17,2026-04-18 00:00:00,2026-04-18 00:00:00,289.000000,-76.000000,0.000000,-92.000000,289.000000,289.000000,121001.000000,121001.000000,2026.0,4.000000,1.000000
25%,3.375447e+17,2026-05-07 00:00:00,2026-05-07 00:00:00,752.000000,-7.000000,0.000000,-7.000000,752.000000,752.000000,412308.000000,412308.000000,2026.0,5.000000,8.000000
50%,4.373556e+17,2026-05-12 00:00:00,2026-05-12 00:00:00,1420.000000,0.000000,0.000000,0.000000,1391.000000,1391.000000,560087.000000,560087.000000,2026.0,5.000000,13.000000
75%,4.375474e+17,2026-05-20 00:00:00,2026-05-20 00:00:00,1420.000000,0.000000,0.000000,0.000000,1420.000000,1420.000000,735063.000000,735063.000000,2026.0,5.000000,22.000000
max,4.376824e+17,2026-05-28 00:00:00,2026-05-28 00:00:00,1916.000000,0.000000,46.000000,0.000000,1916.000000,1916.000000,854318.000000,854318.000000,2026.0,5.000000,30.000000
std,5.015665e+16,NaN,NaN,434.759902,13.971942,7.273414,18.381729,437.588803,437.588803,210814.595953,210814.595953,0.0,0.321418,7.862678

In [27]:
sales_clean.describe().T

,count,mean,min,25%,50%,75%,max,std
Order Item ID,155.0,388508199196818112.0,337364356724775104.0,337544730974203648.0,437355563274297088.0,437547414578855104.0,437682396967212096.0,50156650411921448.0
Order Date,155,2026-05-11 21:31:21.290322688,2026-04-18 00:00:00,2026-05-07 00:00:00,2026-05-12 00:00:00,2026-05-20 00:00:00,2026-05-28 00:00:00,NaN
Order Approval Date,155,2026-05-11 21:31:21.290322688,2026-04-18 00:00:00,2026-05-07 00:00:00,2026-05-12 00:00:00,2026-05-20 00:00:00,2026-05-28 00:00:00,NaN
Price before discount,155.0,1199.535484,289.0,752.0,1420.0,1420.0,1916.0,434.759902
Total Discount,155.0,-7.109677,-76.0,-7.0,0.0,0.0,0.0,13.971942
Seller Share,155.0,1.393548,0.0,0.0,0.0,0.0,46.0,7.273414
Bank Offer Share,155.0,-8.503226,-92.0,-7.0,0.0,0.0,0.0,18.381729
Price after discount (Price before discount-Total discount),155.0,1192.425806,289.0,752.0,1391.0,1420.0,1916.0,437.588803
Final Invoice Amount (Price after discount+Shipping Charges),155.0,1192.425806,289.0,752.0,1391.0,1420.0,1916.0,437.588803
Customer's Billing Pincode,155.0,545079.464516,121001.0,412308.0,560087.0,735063.0,854318.0,210814.595953
Customer's Delivery Pincode,155.0,545079.464516,121001.0,412308.0,560087.0,735063.0,854318.0,210814.595953
Year,155.0,2026.0,2026.0,2026.0,2026.0,2026.0,2026.0,0.0
Month_Number,155.0,4.883871,4.0,5.0,5.0,5.0,5.0,0.321418
Day,155.0,15.380645,1.0,8.0,13.0,22.0,30.0,7.862678

In [28]:
sales_clean.loc[
    sales_clean['Total Discount'] < 0,
    [
        'Price before discount',
        'Total Discount',
        'Bank Offer Share',
        'Price after discount (Price before discount-Total discount)'
    ]
]

,Price before discount,Total Discount,Bank Offer Share,Price after discount (Price before discount-Total discount)
9,1420.0,-28.0,-28.0,1392.0
20,1400.0,-20.0,-40.0,1380.0
22,1374.0,-46.0,-92.0,1328.0
24,1388.0,-32.0,-64.0,1356.0
26,1374.0,-46.0,-92.0,1328.0
27,1374.0,-46.0,-92.0,1328.0
35,752.0,-40.0,-40.0,712.0
39,752.0,-28.0,-28.0,724.0
41,1420.0,-54.0,-54.0,1366.0
44,1807.0,-6.0,-6.0,1801.0
51,1420.0,-29.0,-29.0,1391.0
58,1420.0,-8.0,-8.0,1412.0
61,1394.0,-26.0,-52.0,1368.0
65,752.0,-22.0,-22.0,730.0
68,1420.0,-20.0,-20.0,1400.0
72,752.0,-22.0,-22.0,730.0
75,770.0,-33.0,-33.0,737.0
99,1782.0,-45.0,-45.0,1737.0
101,1782.0,-1.0,-1.0,1781.0
102,762.0,-22.0,-22.0,740.0
108,752.0,-26.0,-26.0,726.0
111,752.0,-8.0,-8.0,744.0
117,752.0,-29.0,-29.0,723.0
118,752.0,-21.0,-21.0,731.0
119,1782.0,-32.0,-32.0,1750.0
125,752.0,-48.0,-48.0,704.0
126,752.0,-29.0,-29.0,723.0
131,762.0,-18.0,-18.0,744.0
132,762.0,-18.0,-18.0,744.0
133,762.0,-29.0,-29.0,733.0
135,762.0,-18.0,-18.0,744.0
136,752.0,-26.0,-26.0,726.0
144,762.0,-29.0,-29.0,733.0
145,762.0,-18.0,-18.0,744.0
148,752.0,-10.0,-10.0,742.0
151,752.0,-21.0,-21.0,731.0
154,752.0,-76.0,-76.0,676.0
155,762.0,-18.0,-18.0,744.0
156,762.0,-18.0,-18.0,744.0
157,762.0,-18.0,-18.0,744.0
158,762.0,-18.0,-18.0,744.0


The **Total Discount** column contains negative values. After validating the calculations, it was observed that the dataset stores discounts as negative amounts.

The relationship is:

Price After Discount = Price Before Discount + Total Discount

Therefore, the negative values represent discount deductions rather than data quality issues. No transformation was applied to preserve the original business records.

In [29]:
sales_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 155 entries, 0 to 160
Data columns (total 28 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Order ID                                                      155 non-null    object
 1   Order Item ID                                                 155 non-null    int64
 2   Product Title/Description                                     155 non-null    object
 3   FSN                                                           155 non-null    object
 4   SKU                                                           155 non-null    object
 5   Event Type                                                    155 non-null    object
 6   Event Sub Type                                                155 non-null    object
 7   Order Type                                                    155 non-null    object
 8   Fulfilment Type                                               155 non-null    object
 9   Order Date                                                    155 non-null    datetime64[ns]
 10  Order Approval Date                                           155 non-null    datetime64[ns]
 11  Price before discount                                         155 non-null    float64
 12  Total Discount                                                155 non-null    float64
 13  Seller Share                                                  155 non-null    float64
 14  Bank Offer Share                                              155 non-null    float64
 15  Price after discount (Price before discount-Total discount)   155 non-null    float64
 16  Final Invoice Amount (Price after discount+Shipping Charges)  155 non-null    float64
 17  Customer's Billing Pincode                                    155 non-null    int64
 18  Customer's Billing State                                      155 non-null    object
 19  Customer's Delivery Pincode                                   155 non-null    int64
 20  Customer's Delivery State                                     155 non-null    object
 21  Is Shopsy Order?                                              155 non-null    bool
 22  Beneficiary Name                                              155 non-null    object
 23  Year                                                          155 non-null    int32
 24  Month                                                         155 non-null    object
 25  Month_Number                                                  155 non-null    int32
 26  Day                                                           155 non-null    int32
 27  Weekday                                                       155 non-null    object
dtypes: bool(1), datetime64[ns](2), float64(6), int32(3), int64(3), object(13)
memory usage: 32.2+ KB

In [30]:
sales_clean.rename(columns={
    'Order ID': 'order_id',
    'Order Item ID': 'order_item_id',
    'Product Title/Description': 'product_name',
    'FSN': 'fsn',
    'SKU': 'sku',
    'Event Type': 'event_type',
    'Event Sub Type': 'event_sub_type',
    'Order Type': 'order_type',
    'Fulfilment Type': 'fulfilment_type',
    'Order Date': 'order_date',
    'Order Approval Date': 'order_approval_date',
    'Price before discount': 'price_before_discount',
    'Total Discount': 'total_discount',
    'Seller Share': 'seller_share',
    'Bank Offer Share': 'bank_offer_share',
    'Price after discount (Price before discount-Total discount)': 'price_after_discount',
    'Final Invoice Amount (Price after discount+Shipping Charges)': 'final_invoice_amount',
    "Customer's Billing Pincode": 'billing_pincode',
    "Customer's Billing State": 'billing_state',
    "Customer's Delivery Pincode": 'delivery_pincode',
    "Customer's Delivery State": 'delivery_state',
    'Is Shopsy Order?': 'is_shopsy_order',
    'Beneficiary Name': 'beneficiary_name',
    'Year': 'year',
    'Month': 'month',
    'Month_Number': 'month_number',
    'Day': 'day',
    'Weekday': 'weekday'
}, inplace=True)

In [31]:
sales_clean.columns

Index(['order_id', 'order_item_id', 'product_name', 'fsn', 'sku', 'event_type',
       'event_sub_type', 'order_type', 'fulfilment_type', 'order_date',
       'order_approval_date', 'price_before_discount', 'total_discount',
       'seller_share', 'bank_offer_share', 'price_after_discount',
       'final_invoice_amount', 'billing_pincode', 'billing_state',
       'delivery_pincode', 'delivery_state', 'is_shopsy_order',
       'beneficiary_name', 'year', 'month', 'month_number', 'day', 'weekday'],
      dtype='object')

In [67]:
sales_clean.to_csv(
    r"D:\flipkart_data\data\cleaned\cleaned_sales_data.csv",
    index=False
)

PermissionError: [Errno 13] Permission denied: 'D:\\flipkart_data\\data\\cleaned\\cleaned_sales_data.csv'

In [68]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in d:\anaconda\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in d:\anaconda\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in d:\anaconda\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [73]:
from sqlalchemy import create_engine
import pandas as pd
username="postgres"
password="irfan123"
host="localhost"
port="5432"
database="sales_analysis"
engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name="sales"
sales_clean.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into the table '{table_name}' in database '{database}'.")

Data successfully loaded into the table 'sales' in database 'sales_analysis'.

In [32]:
sales_clean.head(10)

,order_id,order_item_id,product_name,fsn,sku,event_type,event_sub_type,order_type,fulfilment_type,order_date,...,billing_state,delivery_pincode,delivery_state,is_shopsy_order,beneficiary_name,year,month,month_number,day,weekday
0,OD337392281679223100,337392281679223100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Return,Return,Postpaid,NON_FBF,2026-04-25,...,Maharashtra,411045,Maharashtra,False,Shailee Verma,2026,April,4,25,Saturday
1,OD337442494105588100,337442494105588100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Return,Return,Postpaid,NON_FBF,2026-04-30,...,West Bengal,736146,West Bengal,False,Joydeep Barman,2026,April,4,30,Thursday
2,OD437539555726276100,437539555726276101,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,Prepaid,NON_FBF,2026-05-12,...,Uttar Pradesh,209306,Uttar Pradesh,False,Gunjan Tripathi,2026,May,5,12,Tuesday
3,OD437517196866690100,437517196866690100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-09,...,Karnataka,584125,Karnataka,False,Nida Fatima,2026,May,5,9,Saturday
4,OD437517262241051100,437517262241051100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-09,...,Andhra Pradesh,530045,Andhra Pradesh,False,Byna Jayasree,2026,May,5,9,Saturday
5,OD437419306208738100,437419306208738100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Return,Return,Prepaid,NON_FBF,2026-04-28,...,Karnataka,562125,Karnataka,False,Suresh,2026,April,4,28,Tuesday
6,OD337507936581123400,337507936581123400,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,PartPaid,NON_FBF,2026-05-08,...,Karnataka,570007,Karnataka,True,Imran Baig,2026,May,5,8,Friday
7,OD337458298284925100,337458298284925100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,Postpaid,NON_FBF,2026-05-02,...,Tamil Nadu,635107,Tamil Nadu,False,Sekar Deva .M,2026,May,5,2,Saturday
8,OD337501032148051100,337501032148051100,"""""""WEEGRO Plastic Coffee Table Finish Color - ...","""""""CFTHGMJZGMGDGXZC""""""","""""""SKU:WEEGRO-CT-PLASTIC""""""",Sale,Sale,Postpaid,NON_FBF,2026-05-07,...,Madhya Pradesh,474003,Madhya Pradesh,False,Rukmani,2026,May,5,7,Thursday
9,OD337502241577583100,337502241577583100,"""""""WEEGRO Engineered Wood Coffee Table Finish ...","""""""CFTGDDBYMAZQCQ8X""""""","""""""SKU:WEEGRO-CT-M1""""""",Sale,Sale,Prepaid,NON_FBF,2026-05-07,...,Bihar,811307,Bihar,False,Mohd Arfat,2026,May,5,7,Thursday